### ISSUE TITLE
adding a requirements.txt for a fast configuring environment

### ISSUE THREAD

**Issue by zgcao** [acolite/acolite#27]
Hi Quinten,

In recent, I switched Anaconda to Miniconda to reduce installing space. But, I always need to install the required package one by one after running once.

I would like to suggest adding a requirements.txt to include all Python packages(such as numpy==1.22.0....) used in the development. Such a document may be helpful to configure the ACOLITE environments. 

Regards,
Zhigang

**Comment by acolite** [comment]
Hi Zhigang

I am not sure what you mean with installing the required packages one by one. Did you try the conda install guide in the main repository ReadMe? https://github.com/acolite/acolite#dependencies

I can provide the package lists in the Linux/Mac/Windows conda environments I use here for the binary generation.

Quinten

**Comment by zgcao** [comment]
Hi Quinten,

When I used Miniconda (just wanna reduce installation space), other some packages were still required besides the dependencies in ReadMe.txt.  I am not sure whether I missed somethings using conda. 

I just suggest that a package list may be helpful for a fully new installation, for example, using pip install requirements.txt :).

Zhigang

**Comment by acolite** [comment]
Hi Zhigang

I use miniconda myself and have not had issues with setting up new ACOLITE environments (on Linux/Mac/Windows) like this (as in https://github.com/acolite/acolite#dependencies):

```
conda create -n acolite -c conda-forge python=3
conda activate acolite
conda install -c conda-forge numpy matplotlib scipy gdal pyproj scikit-image pyhdf pyresample netcdf4 h5py requests pygrib astropy cartopy
```

It is not necessary to use pip to install these in a conda environment, and if you do use pip you may run into issues. (Here is a short post on this: https://www.anaconda.com/blog/using-pip-in-a-conda-environment) In general it is probably best not to mix both conda and pip if it is not essential. I use conda since I find it easy to use, and really good at handling multiple, and reproducible environments. I do occasionally use pip, but not for ACOLITE, and always within separate environments.

Attached here is a requirements.txt file that I generated from a "zhigang" environment created as above, running pip only to list the requirements. Note that pip was only used to create dependencies.txt:

```
conda create -n zhigang -c conda-forge python=3
conda activate zhigang
conda install -c conda-forge numpy matplotlib scipy gdal pyproj scikit-image pyhdf pyresample netcdf4 h5py requests pygrib astropy cartopy
pip list --format=freeze > requirements.txt
```

I tried installing with pip from the requirements.txt in a new environment, but this failed during installation of cartopy with a GEOS versioning conflict (which I did not try to resolve):

```
conda create -n zhigang2 -c conda-forge python=3 pip
conda activate zhigang2
pip install -r requirements.txt
```

**I cannot recommend using this requirements.txt file but I include it here since you have asked for it. This file does not come from a working acolite environment created with pip!**

I can recommend the use of the spec or YAML files generated from the first zhigang environment created above (the YAML file is essentially reproducing the command installing packages from conda forge above):

```
conda activate zhigang
conda list --explicit > spec-file.txt
conda env export > environment_full.yml
conda env export --from-history > environment.yml
conda deactivate
```

The spec file does contain references to the platform (in this case linux64) so this may not work cross platform. Similarly the "full" YAML file contains references to specific package builds which may not be available for all platforms. I have zipped the YAML files to comply with GitHub attachment file types.

You can use either the YAML or spec file to replicate this environment (here changing the --name from what is specified in the YAML file):

```
conda env create --name acolite --file environment.yml
```
or
```
conda create --name acolite --file spec-file.txt
```

Both these environments created with conda from the spec and YAML files were tested by processing a Sentinel-2 scene:

```
conda activate acolite
python acolite/launch_acolite.py --cli --settings settings.txt
conda deactivate
```

I am curious to see your installation method, and to know which packages you had to install separately.

I hope this helps!

Quinten

Attachments:
[requirements.txt](https://github.com/acolite/acolite/files/8321983/requirements.txt)
[spec-file.txt](https://github.com/acolite/acolite/files/8321984/spec-file.txt)
[environment_full.yml.zip](https://github.com/acolite/acolite/files/8321980/environment_full.yml.zip)
[environment.yml.zip](https://github.com/acolite/acolite/files/8321981/environment.yml.zip)

**Comment by zgcao** [comment]
Hi Quiten,

I recreated a new python3 environment with miniconda, and installed dependencies following your comments, now it works well. Every is okay. I do not know why the same operation before still required other packages. It maybe due to the unexpected settings in old conda environment.

Thanks.
Zhigang

**Comment by acolite** [comment]
Hi Zhigang

Thanks for the update, and I am glad you could set up a working environment! Indeed maybe there were some issue with your previous environment with other explicitly installed packages.

Quinten
