### ISSUE TITLE
Running the latest version of Acolite to process Sentinel-2 in a Windows computer I get this message.

### ISSUE THREAD

**Issue by cyandee** [acolite/acolite#32]
When I use the Acolite GUI interface to perform atmospheric correction on Sentinel-2 L1C, I get an "UnboundLocalError: local variable 'pr' referenced before assignment". What is this? I have python environment on my computer, I don't know if this is related to this, please tell me how to solve this problem, thanks a lot!
![](https://raw.githubusercontent.com/cyandee/Image/main/img/acolite_error.png)
![](https://raw.githubusercontent.com/cyandee/Image/main/img/LUTs.png)

**Comment by acolite** [comment]
Hi

I think this error occurs because the band files cannot be found, either as a result of a too long path to the SAFE directory, or due to path length issues in the extraction software. To resolve, move the SAFE to or extract the zip file at a lower level directory: https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?f=4&t=346

This should have been resolved with this commit: https://github.com/acolite/acolite/commit/e5c51a4a2d6dc06fcabbeff1402992c7fb828ec2 and the fix will be included in future binary versions.

Quinten
