### ISSUE TITLE
Difficulties changing S3 output projection

### ISSUE THREAD

**Issue by EmanuelCastanho** [acolite/acolite#64]
Hi,

I am processing the following Sentinel-3 product: `S3A_OL_1_EFR____20190706T155927_20190706T160227_20190707T201131_0179_046_325_2520_LN1_O_NT_002.SEN3`

I want to apply atmospheric correction, crop and obtain geoTIFF outputs, however I am having difficulties setting up `settings['output_projection_epsg'] = '4326'`.

I am using a `limit` based on a ROI extracted from SentinelHub EOBrowser (EPSG:4326): `{"type":"Polygon","coordinates":[[[-88.000488,21.375081],[-88.000488,22.108543],[-86.833191,22.108543],[-86.833191,21.375081],[-88.000488,21.375081]]]}`.

These options:
```
settings['reproject_before_ac'] = True
settings['output_projection'] = True
settings['netcdf_projection'] = False
settings['output_projection_epsg'] = '4326'
settings['l2w_export_geotiff'] = True
```

Are giving me the following error:
`Number of samples, -3, must be non-negative.`

I would like to have the exact crop accordingly to the EOBrowser ROI, but I see here [Reprojection and GeoTIFF outputs for Sentinel-3](https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?t=361) that this is not so straightforward. Any advice?

If I ignore the `output_projection_epsg`, this is what I obtain when visualising on QGIS:

![Screenshot 2023-06-09 at 17 16 12](https://github.com/acolite/acolite/assets/69935277/e7c1f447-842e-4657-8634-6a3929d7a1d7)

Thank you!

**Comment by acolite** [comment]
HI Emanuel

For best results I would recommend you do your own reprojection of the NetCDF outputs. I added this built-in reprojection more as an experimental function.

The projection boundaries are estimated from the limit, but for most projections you probably have a fixed x and y extent and pixel size. These can be configured as well, do you have an example GeoTIFF file that is to your specifications?

When you don't specify an EPSG a UTM projection will be used with default pixel resolution set for OLCI (300 metres). I believe when you specify EPSG:4326 the resolution should be in degrees rather than metres. After setting:

settings['output_projection_epsg'] = 'EPSG:4326'
settings['default_projection_resolution'] = [0.01,0.01]

I get outputs, but they are completely white. To be checked what is causing this! By switching to a NN resampling I get outputs, but they are not as smooth as the bilinear resampling:

settings['output_projection_resampling_method'] = 'nearest'
settings['output_projection_radius'] = 30000

I hope this helps!

Quinten

**Comment by EmanuelCastanho** [comment]
I am used to work with Sentinel-2, so for me this new Sentinel-3 reprojection is a bit confusing.

I don't have an example GeoTIFF. A GeoTIFF file with the same extent as my specified ROI, 300 m of spatial resolution and UTM projection it would be fine. I only don't understand why there is a small mismatch between the ROI and the final GeoTIFF when visualising on QGIS. Why it is not a perfect match?

Also, and maybe this is a topic for another issue, EARTHDATA credentials are provided inside the output netCDF. Can we disable ACOLITE from sharing this sensitive information in the netCDF?

**Comment by acolite** [comment]
Hi Emanuel

A projected grid has an extent and a pixel size, which determine the output pixel dimensions. This grid cannot align with any arbitrary limit. For example, you cannot fit an integer number of 0.3 degree pixels in a 2 degree extent. Similarly, you cannot fit an integer number of 300 metre pixels in a 5 km extent. EPSG:4326 is not a projection per se, but it can be constructed as an equirectangular grid. In this projection you also need to specify a pixel size, and you can see your limit and pixel size need to be adjusted to get a perfect match. For example, you can fit an integer number of 0.3 degree pixels in a 2.1 degree extent. (Not that projection to EPSG:4326 is working properly in ACOLITE at the moment!)

The slight rotation you see between the ACOLITE output and the original ROI on your screenshot is caused by differences in projection, where ACOLITE uses UTM by default. EPSG:4326 as an equirectangular projection is not conformal (i.e. it does not preserve angles) or equal area (i.e. it does not preserve area), whereas Mercator projections are conformal.

You can get a bit more control over the projection by specifying the x and y ranges (in metres when using UTM) by providing x1,x2 and y1,y2:

```
output_projection_resolution=300,300
output_projection_metres=True
output_projection_xrange=x1,x2
output_projection_yrange=y1,y2
```

For the credentials, this is a good point. At the moment you can use a netrc file (.netrc on Linux/Mac or _netrc in Windows) to store them, or set them as environment variables when running ACOLITE.

I hope this helps!

Quinten

**Comment by acolite** [comment]
It is possible to get the bilinear reprojection to EPSG:4326 working by further increasing the output_projection_radius, e.g.:

settings['output_projection_radius']=1e6

If you get projection artefacts you may need to increase the neighbourhood:

settings ['output_projection_neighbours']=64

Quinten
