### ISSUE TITLE
l2w water parameter, and water mask 

### ISSUE THREAD

**Issue by Abdelmaged66** [acolite/acolite#71]
I m new to using acolite, so using GUI of it,  for S2.
To get Rrs with water mask with target RP 10m.

**Comment by acolite** [comment]
Dear Abdel

I am not sure what exactly you are asking. Have you taken a look at the ACOLITE [manual](https://github.com/acolite/acolite/releases/latest) and [forum](https://odnature.naturalsciences.be/remsem/acolite-forum/)?

By default Sentinel-2 data are processed at 10 m resolution (s2_target_res=10) and to get Rrs you have to specify it as an output parameter (l2w_parameters=Rrs_*). The default non-water masking will be applied to the output L2W products.

I hope this helps!

Quinten

**Comment by Abdelmaged66** [comment]
Good morning

thanks for your reply,  that  was very helpful but after doing the process
in prompt to process my setting file

"## ACOLITE settings
## Written at 2024-01-25 13:20:13
inputfile=C:/Users/amaged/Desktop/DATOSSENTENAL/CHiprana/S2A_MSIL1C_20230614T105031_N0509_R051_T31TBF_20230614T143035.SAFE
output=C:/Users/amaged/Desktop/DATOSSENTENAL/CHiprana/OUTCHL/out14062023
polygon=None
l2w_parameters= rhow_*,Rrs_*
rgb_rhot=True
rgb_rhos=True
map_l2w=True
l2w_export_geotiff=True
runid=20240125_132012
new_path=None"


I used the source as acolite but it took like 2h (my pc not bad ) to
finish that and the result I will attach my photo. I did not get my AOI for
my water surface lake.
I am asking about how to solve that, and can make changes or modify the
default.txt.

[image: image.png]

**Comment by Abdelmaged66** [comment]
![acolite](https://github.com/acolite/acolite/assets/124809192/8a743c53-4aa9-407e-97cb-0f5fb5c4a3a6)
the photo againe couse firts not ubloded,  my lake very small but acolite with defuelt dont mask or extract it, loosing all water pixels

**Comment by acolite** [comment]
Hi Abdel

I recommend not to change any defaults, but rather work with user defined settings files with minimal content: https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?f=5&t=320 You could start e.g. by modifying the settings_user.txt file output by ACOLITE.

I would include a limit to crop the image if you are processing the scene to look at a small lake. This will surely help with processing time. You can specify a S,W,N,E coordinate bounding box in your settings file, for example:

```
limit=41.2343,-0.1905,41.2447,-0.1759
```

Gives:
![S2A_MSI_2023_06_14_10_59_49_T31TBF_L2R_rgb_rhos](https://github.com/acolite/acolite/assets/26734727/e4e627dc-0706-4512-a57b-94abfe648669)

For the data being masked I would look at this post on the forum: https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?f=5&t=311 In your case it seems there is some sun glint which is masking your data. You can change masking settings, e.g.


```
l2w_mask_threshold=0.08
l2w_mask_smooth=False
```

Gives at 560 nm:
![S2A_MSI_2023_06_14_10_59_49_T31TBF_L2W_rhow_560_noglint](https://github.com/acolite/acolite/assets/26734727/33b72d29-626b-4077-9a91-ebd927273536)

and perhaps also apply a glint correction (note to also increase the glint masking threshold):

```
dsf_residual_glint_correction=True
glint_mask_rhos_threshold=0.08

```

Which gives at 560 nm:
![S2A_MSI_2023_06_14_10_59_49_T31TBF_L2W_rhow_560_glint](https://github.com/acolite/acolite/assets/26734727/dfa82046-1f61-474a-af90-f7ef8a5914fe)

Note that here additional pixels are masked due to the retrieval of negatives after the glint correction. I leave it to you to decide whether to include negatives in your analysis, and to figure out how to disable this masking! :-) Changing the threshold also removes the masking the cloud shadow area.

Since this is not a technical issue with ACOLITE I will close this issue, and would recommend you to register and post on the forum for this kind of question.

I hope this helps!

Quinten

**Comment by Abdelmaged66** [comment]
Hi, Quinten
I need to obtain the chl-a map using the  chl_re_moses3b740, but with this
modification :

limit=41.2343,-0.1905,41.2447,-0.1759
l2w_parameters=chl_oc2, chl_oc3,chl_re_gons, chl_re_gons740,chl_re_moses3b,
chl_re_moses3b740,chl_re_mishra,chl_re_bramich
l2w_mask_threshold=0.08
l2w_mask_smooth=False
glint_force_band=1600
glint_mask_rhos_band=1600
glint_mask_rhos_threshold=0.15
rgb_rhot=True
rgb_rhos=True
map_l2w=True

but i missed many pixels and the clouds without masking.

many thanks,
Abelmaged

**Comment by acolite** [comment]
For which inputfile?

Have you checked the l2_flags to understand the masking?
